# Generated by Django 2.2.1 on 2021-10-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='mobile',
        ),
    ]
