# Generated by Django 2.2.1 on 2021-10-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('status', models.CharField(blank=True, choices=[('visible', 'Visible'), ('hidden', 'Hidden')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='thumbs')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('visible', 'Visible'), ('hidden', 'Hidden')], max_length=100, null=True)),
                ('stock', models.CharField(blank=True, choices=[('in-stock', 'In Stock'), ('stock-out', 'Out of Stock')], max_length=100, null=True)),
                ('final_price', models.IntegerField()),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='web.Categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='SpecialProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('hot-offer', 'Hot Offer'), ('featured-product', 'Featured Product')], max_length=255)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='web.Products')),
            ],
            options={
                'db_table': 'specialproducts',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Units'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_no', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField(null=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='web.Products')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
