# Generated by Django 2.2.1 on 2021-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
